### PR TITLE
Add examples for Aqualid build system

### PR DESCRIPTION
**Pull request by menify**
I added examples for [Aqualid](https://github.com/aqualid/aqualid) build system.
Thanks.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the patch, looks reasonable. I notice you didn't update the readme.md, can you do that? At the very least a bullet point at the top saying what Aqualid is and where people can find more.

I also test some of the build systems in Travis, see the travis.sh file. If you can run Aqualid on Travis, running the tests would be very useful.

**Comment by menify** [comment]
Thank you.
I have updated the README.md
I'm not familiar with Travis. I will investigate it.

**Comment by ndmitchell** [comment]
For the Travis, there is a file `travis.sh`, so just add the commands to install Aqualid there and the rest probably just works. Alternatively, just leave it, and I'll have a go myself. I'm busy for the next two days, but will hope to merge this request on Thursday.

**Comment by menify** [comment]
Build [#89](https://travis-ci.org/ndmitchell/build-shootout/builds/51191307) on Travis fully passed.
Thank you.

**Comment by ndmitchell** [comment]
Perfect! Thanks a lot.

**Pull request merged**
