### PR TITLE
Add fbuild

### PR DESCRIPTION
**Pull request by kirbyfan64**
I've got some [slight bias here](https://github.com/felix-lang/fbuild/commits?author=kirbyfan64)...

I think I got everything down. Note that fbuild does NOT work on Windows right now (blame code rot), but it will soon, and it still works on Linux and OSX, so I'm marking it as cross-platform. :)

### CODE REVIEW

**Comment by ndmitchell** [comment]
Bias is absolutely fine :) I can't see the fbuild implementations in this patch?

**Comment by kirbyfan64** [comment]
@ndmitchell Whoops. Fixed.

**Comment by ndmitchell** [comment]
For the ones you wrote failure, are these things impossible by design, because you haven't got round to them or other reasons? If any are impossible by design or implementation reasons could you say that? The reason most other entries lack that information is that it's really only something the build system author can say definitively.

**Comment by kirbyfan64** [comment]
@ndmitchell Well...

- intermediate: I actually had a question about this one. Does it actually need to be a *feature*? In Fbuild, I could probably do:

    ```python
    def run(ctx, src: fbuild.db.SRC, dst: fbuild.db.DST):
        ctx.execute(['sh', 'intermediate-run', src, '--', 'intermediate'])
        ctx.execute(['sh', 'intermediate-run', 'intermediate', '--', dst])
        os.remove('intermediate')
    ```

    basically using Python's `os` module.

- system2: I'm not really sure. I don't think so. It *would* be possible if I were to add an ability to remove a specific function instance from the cache, but I'm not sure if I want to do that.

- noleftover, secondary: Unsupported.

I didn't create Fbuild; I'm just the maintainer now because the original guy left. I'm still trying to grasp some implementation details.

**Comment by ndmitchell** [comment]
The existence of a feature is not intended to imply the feature is desirable - I guess for the ones like intermediate where it's more "Make has it" rather than necessarily "it's sensible" I should probably call that out in the docs (the first plan was to figure out the relative power of systems, then decide what was actually sane).

**Comment by ndmitchell** [comment]
For the failing test, do you need to `sudo install python3` first? I haven't looked at the default Travis configurations, although slightly surprised if python3 isn't very easy to get on there.

**Comment by kirbyfan64** [comment]
@ndmitchell So would my example count?

Yeah, I forgot about installing `python3`. Fixed.

**Comment by ndmitchell** [comment]
If you end up using os stuff, I think you probably get a "partial" - you've gone outside the build system, so it's not natively supported in the build system, but it's still possible. But there's a lot of shades of grey there, since while you are going outside the build system, it's hardly rocket science.

**Comment by kirbyfan64** [comment]
@ndmitchell Well, a lot of Python-based build systems end up doing stuff like that, it seems.

I could always rewrite it to use Fbuild's `Path` class wrapper:

```python3
def run(ctx, src: fbuild.db.SRC, dst: fbuild.db.DST):
    ctx.execute(['sh', 'intermediate-run', src, '--', 'intermediate'])
    ctx.execute(['sh', 'intermediate-run', 'intermediate', '--', dst])
    Path('intermediate').remove()
```

:O

**Comment by kirbyfan64** [comment]
Let's try the build again...

**Comment by ndmitchell** [comment]
Seems to have hit throttling on Travis, and I'm off to bed now, but I'll take a look and merge in the morning. I leave you to make a call as to whether it's how you expect things to be done (in which case you succeed), it's stepping out of the normal realm and doing it manually (in which case partial) or it's too vile for words and you don't want to do it (in which case fail). Certainly the `Path` wrapper above looks perfectly reasonable to me.

**Comment by kirbyfan64** [comment]
Everything's done. Travis works and I added the `intermediate` test.

**Comment by ndmitchell** [comment]
Thanks, looks great.

**Pull request merged**
